runtime: python27
api_version: 1
threadsafe: true

skip_files: 
 - ^.*node_modules(/.*)?

handlers:

- url: /static
  static_dir: static 

- url: /.*
  static_files: static/index.html
  upload: static/index.html
